import * as motion from "motion/react-client";

const Footer = () => {
  return (
    <div className="mx-auto mt-20 flex items-center justify-center gap-10 bg-secondary py-10 text-background">
      <motion.div
        initial={{ scale: 0, opacity: 0 }}
        whileInView={{ scale: 0.8, opacity: 1 }}
        viewport={{ once: true }}
        transition={{ duration: 0.6, delay: 0.2 }}
        className="mx-auto flex w-3/4 items-center gap-10"
      >
        <div>
          <h1 className="text-2xl font-semibold">
            Mind<span className="italic">Rush</span>
          </h1>
        </div>

        <div className="text-lg font-semibold">
          © 2025 - MindRush. This site is a fictional academic project developed for educational
          purposes. No information here represents a real entity. All information was generated by
          AI.
        </div>
      </motion.div>
    </div>
  );
};

export default Footer;
