Table educator {
  id uuid [primary key]
  name string [not null]
  email string [not null, unique]
  password string [not null]
  created_at timestamp [not null, default: `CURRENT_TIMESTAMP()`]
}

Table quiz {
  id uuid [primary key]
  educator_id uuid [not null]
  title string [not null]
  description string [not null]
  created_at timestamp [not null, default: `CURRENT_TIMESTAMP()`]
}

Table question {
  id uuid [primary key]
  quiz_id uuid [not null]
  type enum('QUIZ', 'TRUE_OR_FALSE')
  question string [not null]
  time_limit integer [not null]
  created_at timestamp [not null, default: `CURRENT_TIMESTAMP()`]
}

Table question_quiz_alternatives {
  id uuid [primary key]
  question_id uuid [not null]
  answer string [not null]
  correct boolean [not null]
  created_at timestamp [not null, default: `CURRENT_TIMESTAMP()`]
}

Table match {
  id uuid [primary key]
  quiz_id uuid [not null]
  pin string [not null]
  state enum('WAITING', 'RUNNING', 'PAUSED', 'ENDED') [not null]
  created_at timestamp [not null, default: `CURRENT_TIMESTAMP()`]
}

Table participant {
  id uuid [primary key]
  nickname string [not null]
  match_id uuid [not null]

  indexes {
    (nickname, match_id) [unique]
  }
}

Table quiz_answer {
  id uuid [primary key]
  participant_id uuid [not null]
  question_id uuid [not null]
  match_id uuid [not null]
  alternative string [not null]
  created_at timestamp [not null, default: `CURRENT_TIMESTAMP()`]

  indexes {
    (participant_id, question_id, match_id) [unique]
  }
}

Ref: "educator"."id" < "quiz"."educator_id"
Ref: "quiz"."id" < "match"."quiz_id"
Ref: "quiz"."id" < "question"."quiz_id"
Ref: "question"."id" < "question_quiz_alternatives"."question_id"
Ref: "match"."id" < "participant"."match_id"
Ref: "participant"."id" < "quiz_answer"."participant_id"
Ref: "question"."id" < "quiz_answer"."question_id"
Ref: "match"."id" < "quiz_answer"."match_id"
